services:
  - docker

sudo: required

before_install:
  - docker-compose pull
  - docker-compose build

script:
  - docker-compose run rom bundle exec rspec

after_success:
  - bundle exec codeclimate-test-reporter

env:
  global:
    - secure: "y+WKE+O64Mk9/MIiVDsHY12FsIDv31c5kGT1PD8X3bGzDLSs2RsxH+6aAPKj8soQIU6vN1cpXzHOI9rmgSa/jPwXN/TVhXNQUEaQGaCQjlucx4D7M0SjXxrEVcFsXeQpkb+sDH7zeRDj9mxnpzpHzFc1uLBodKUKFoqDJP67rYzdfHYTGettvGxPBR38gZxSPGejVNbb+cnY8bvUECK/Qn+0MTR3xjkZi+y4PKsj4ZlN7+4m8GOQt/S/9SK++5MJtlXXRtC7tufXZ3QJvmyfB/FbDYm5/e+ovAWVFI2s62/IuE5qdoEjBK3j8cKvTErrBzp1mo9JtM1QeJGAGuOroM8ki9cjPV+mtuFdIq7pzjBOK8ZIWGCQCljuIvyWZ88jZQzqkjgcREvBxGJa5u/maaNduUXWdfR/Q2DFazX7SfrD5CLXvinemVdPpo8/D0NhduSW8pgSKF0E9WBGng2z3BP40L+l7aTFfzrrirdzDNU1KsOzfDDs9+h9Rq8uwIhKiZhiPr+4ztXteNmaJMaeL9KnAgIhZGW1EYUkC1gAVXRkzaFFh3tnRhKAzU1LJxl2qskf0MJFgc/hr3hTHvWgYCQYe2QCZdulqb7HdnUH55Twsha+XVtMp25GxKVrTN4ET5L971xALGvTRxKaO2lekZmVxr4qauhyoXMUc1pCN4g="
    - secure: "kQuM1k5J7COei8KyvabP/YROhoUFlLZkieaDQLFyOj2cobYW6bYsfzuWkNKaNpBrVjEenumLHwHg6P9vVmI7FQ1IEUW2QkAYSUUni/jRBK53jICIINWo6YLWgLQdpdkBnCzMv8MVXBlrqLgqcUn3aUXEtOhM9uHQbhknBx+z+Yja8tdjt6m8scBmqGj8a3zH3Pypi0PbH7fNHUXzAGx/CUyB/s58zUkm9SRs7uR5TRVKtmUyXaroTxmKL9iDIuArjMsOTzu/Xr1kwdlg1kmzB//j0basRzYPOSNdJAGKEdwXo6ul7ZGc993iIJGS/+LZuLgrOcdjHklBSWlduQABEqOFpL76cG7RUH5Mo58Wqd+ftR/Lz5+vEDxpj1JXOUzKv4yB/EA3hTxnK7vCvp5pYSAD+sqtTn5f8TpcxaKYwR0n5YUtV9E8JhZ4I5QvWONU1zXsb9ulhGBFRhZniFKNEsBoapdCA+rAEXLJS0D7ODEE7degsv1uMhO6QPt1sAWvHZvZh01XvlEM9p7aeTOnD72DjKw47GTU/GL6Ekl8er+wubk/ZGBKMQ9YZXiT2jQwgIJyKSWw19s0Ru9otLhrSgwY0eHhvQuyYWL2DwFV2Bcrx1Glgj96+nSzj8g/42NTL1fX5cYAAPYjnqWLc8yuqF+ioF24Yq22CuTQhn/u0BE="

addons:
  code_climate:
    repo_token:
      secure: "AL3aOEHyWvXkXGne+U3n6ToU0Ubp8yiy3y6gqo/IF2DsN133ynEwcUsif81eIeMTYa+LH4PfDV4iImbwrawhJdyr1ghAqC98k2xfzD5oBSOO8b6gj5k3fRLGRIlGcFwrSSZm9t3F3J3teU3QeaeOW5QhJrtGtlApVvMRzUQPmPbFKjSbzg9oXnl6rWpghUGPjkJZ1zJARZqYx6yJ5JYoRFX7xPcwmwvMa3tCnLh3wfpVCexsa33gssFCGUuh/qU2aLO9f/EyLV95nkxNoXdNoMAajuddDAUK2GQSBLuGijyydUl+x9ZLEsfMJbW3xFqeYVQzMiRXMku0kp7NuzSF9TfPP4TSv5EIJAuVujB3u7sc+jRGEy+m+WawUunu8BmX1l9vjBMcMUonqcsToTBHf9u1nLBdJMhwk0WQkvcJ31g4lrc5y4wut/mRdylBTrplAJAwcHfXnM7ADWL4DN3Yx+Vo+lPgkCrtnsMST2PUcyW2v+hln/BR9qB9PGPC121o7D+BNNuT4oLrw7tebnl3CWI9cpb2jaZl1cVrINhOnApukO1oqxOE2xGVCkNIZ4RIDLlj1WVbbLBN/C/dREjf6n/jNT5LylWEULHofYpit2+1o8KSHjT7aCMLwWlyIuAyYz45WSPviy4oyrjeLUGUo3u15EjJeGcKhXtrtreVdvk="

deploy:
  provider: rubygems
  api_key:
    secure: "sg3BZImJ6Tr6Gs76acTVVuK405wVdsodQSfozR24ZG4vPMyWtRw9gkC0L0C+3pGo9MU1RvgvnxMtJ5A/XdK1w4vf09lY1nUf2RIS0M5R1uJUojl/v5fZNBdzHNHtvFevTH6Ytcu5DYdyp7YDqUAeORG1zM903GKndq2nVO5jXFvW/2QdwmnTqY1yd/jFmxBrRF1MVcijmxSuOEyI6g8ePXInG/zke+lEtDXxxmPlsCRwajjXL6uOR7NcpwljsDdGKCz48fXPWjXKGEPCWFvl39jIc2WAXuvoMJpwvTpj8BeCdYSLc7bM8lVXNSTBijvjPOakd0Kv6ptdgKuAmHVlSKm1eRoOl8NXaGLJR4s1cHWYAfh267oaANZh+8qsbod3ZV1KC648a6GJXjbyQ8xH3mOs0bCEYRJANRVlkZ+W3+FRikpRsMAKk22EYO3oRvKw74/CSjvHRPSBoFqQTFdWVQQOHDGbUZ5TQul/+N3MiPSXUYhCocrsQXxpxHWdZwYpL32Dz8q5Y44sPDmuYBzOjVZ44ORFAtIXoM9no59jvdjGKnwtZdtvFN2ScuTJxhf7ykOFe0u1ksFwghBADiusF3lyv+MXiCHWlS6vOADMrHSxJIW6i1kzB5BGfajFAtIfLncM5MeBXMUPtQy/EbVHvTVKeqVKhHBObB72WXBdcQM="
  on:
    tags: true
